import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "./component/client/Nav";
import Footer from "./component/client/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SPE - Société Pontivyenne d'Electricité",
  authors: [
    {
      name: "SPE",
      url: "https://spe.bzh",
    },
  ],
  creator: "SPE",
  keywords: [
    "SPE",
    "Société Pontivyenne d'Electricité",
    "électricité",
    "plomberie",
    "chauffage",
    "domotique",
    "Pontivy",
    "Bretagne",
  ],
  openGraph: {
    title: "SPE - Société Pontivyenne d'Electricité",
    description:
      "Votre expert en électricité, plomberie, chauffage et domotique à Pontivy.",
    url: "https://spe.bzh",
    siteName: "SPE - Société Pontivyenne d'Electricité",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className="bg-base-100">
        <>
          <Nav />
          {children}
          <Footer />
        </>
      </body>
    </html>
  );
}
